version: "3.7"
services:
  task_db:
    container_name: task_pgdb
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./scripts/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql:ro
      - /opt/core_db:/var/lib/postgresql/data
    networks:
      - challenge

networks:
  challenge:
    driver: bridge

    name: challenge
